version: '3.8'

services:
  postgres:
    container_name: postgres
    hostname: postgres
    image: postgres:15
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-pass}
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
    ports:
      - 5432:5432